version: "3.9"
services:
  db:
    image: postgres:13-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres

  wallet:
    build:
      context: .
      dockerfile: ./docker/wallet/Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    environment:
      DATABASE_DSN: postgresql://postgres:postgres@db:5432/postgres
      DATABASE_TYPE: psql
      ACCESS_API_HOST: https://access-testnet.onflow.org
      CHAIN_ID: flow-testnet
    depends_on:
      - db
