version: "3.9"
services:
  db:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  emulator:
    container_name: flow-emulator
    image: flow-cli:0.21.0
    command: emulator -v
    ports:
      - "3569:3569"
      - "8080:8080"
    volumes:
      - "./:/app"
    environment:
      - FLOW_SERVICEPRIVATEKEY=${ADMIN_PRIVATE_KEY}
      - FLOW_SERVICEKEYSIGALGO=ECDSA_P256
      - FLOW_SERVICEKEYHASHALGO=SHA3_256
