version: "3.9"
services:
  db:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=wallet
      - POSTGRES_USER=wallet
      - POSTGRES_PASSWORD=wallet

  wallet:
    build:
      context: .
      dockerfile: ./docker/wallet/Dockerfile
      network: host # docker build sometimes has problems fetching from alpine's CDN
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    restart: unless-stopped
    environment:
      FLOW_WALLET_DATABASE_DSN: postgresql://wallet:wallet@db:5432/wallet
      FLOW_WALLET_DATABASE_TYPE: psql
      FLOW_WALLET_ACCESS_API_HOST: emulator:3569
      FLOW_WALLET_CHAIN_ID: flow-emulator
    depends_on:
      - db
      - emulator

  emulator:
    image: gcr.io/flow-container-registry/emulator:v0.23.0
    command: emulator -v
    ports:
      - "3569:3569"
    environment:
      - FLOW_SERVICEPRIVATEKEY=${FLOW_WALLET_ADMIN_PRIVATE_KEY}
      - FLOW_SERVICEKEYSIGALGO=ECDSA_P256
      - FLOW_SERVICEKEYHASHALGO=SHA3_256
