version: "3.9"
services:
  db:
    image: postgres:13-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres

  wallet:
    build:
      context: .
      dockerfile: ./docker/wallet/Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    environment:
      DATABASE_DSN: postgresql://postgres:postgres@db:5432/postgres
      DATABASE_TYPE: psql
      ACCESS_API_HOST: emulator:3569
      CHAIN_ID: flow-emulator
    depends_on:
      - db
      - emulator

  emulator:
    build:
      context: ./docker/flow-cli
    restart: unless-stopped
    command: emulator -v
    environment:
      - FLOW_SERVICEPRIVATEKEY=${ADMIN_PRIVATE_KEY}
      - FLOW_SERVICEKEYSIGALGO=ECDSA_P256
      - FLOW_SERVICEKEYHASHALGO=SHA3_256
