openapi: 3.0.3

info:
  title: Flow Wallet Service API
  version: 0.0.1

servers:
  - url: http://localhost:3000/v1

components:
  schemas:
    account:
      type: object
      properties:
        address:
          type: string
          example: "0xf8d6e0586b0a20c7"
        createdAt:
          type: string
          example: "2021-04-27T05:49:53.211+00:00"
        updatedAt:
          type: string
          example: "2021-04-27T05:49:53.211+00:00"

    transaction:
      type: object
      properties:
        transactionId:
          type: string
          example: "9613c9689a50a5ed9198dc43839cd90ef39203dfdd7ab54f0fc5ca12f256eef0"
        createdAt:
          type: string
          example: "2021-04-27T05:49:53.211+00:00"
        updatedAt:
          type: string
          example: "2021-04-27T05:49:53.211+00:00"

    job:
      type: object
      properties:
        jobId:
          type: string
          example: "717c25c2-4b54-4588-8f83-72f37ae1a0e8"
        status:
          type: string
          example: "Accepted"
        result:
          type: string
          example: ""
        createdAt:
          type: string
          example: "2021-04-27T05:49:53.211+00:00"
        updatedAt:
          type: string
          example: "2021-04-27T05:49:53.211+00:00"

    script:
      type: object
      properties:
        code:
          type: string
        arguments:
          type: array
          items:
            type: object
            properties:
              type:
                type: string
              value:
                type: string

    cadenceValue:
      type: object
      properties:
        Value:
          type: string

    plainValue:
      type: string

  parameters:
    limit:
      name: limit
      description: The maximum number of items to return. -1 disables the limit. If no limit is given (or limit=0) 1000 is used as a default.
      in: query
      required: false
      schema:
        type: integer
        minimum: -1
        example: 1000

    offset:
      name: offset
      description: The number of items to skip before starting to collect the result set.
      in: query
      required: false
      schema:
        type: integer
        minimum: 0
        example: 0

    address:
      name: address
      in: path
      required: true
      schema:
        type: string
        example: "0xf8d6e0586b0a20c7"

    jobId:
      name: jobId
      in: path
      required: true
      schema:
        type: string
        example: "717c25c2-4b54-4588-8f83-72f37ae1a0e8"

    tokenName:
      name: tokenName
      in: path
      required: true
      schema:
        type: string
        enum: [FLOW, FUSD]
        example: FLOW

    transactionId:
      name: transactionId
      in: path
      required: true
      schema:
        type: string
        example: "9613c9689a50a5ed9198dc43839cd90ef39203dfdd7ab54f0fc5ca12f256eef0"

paths:
  /jobs:
    get:
      summary: List all jobs
      parameters:
      - $ref: "#/components/parameters/limit"
      - $ref: "#/components/parameters/offset"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/job"

  /jobs/{jobId}:
    parameters:
    - $ref: "#/components/parameters/jobId"
    get:
      summary: Get a job
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/job"

  /accounts:
    get:
      summary: List all accounts
      description: Get a list of all accounts managed by the wallet service.
      parameters:
      - $ref: "#/components/parameters/limit"
      - $ref: "#/components/parameters/offset"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/account"
    post:
      summary: Create an account
      description: Create a new account that will be managed by the wallet service. Returns a job.
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/job"

  /accounts/{address}:
    parameters:
    - $ref: "#/components/parameters/address"
    get:
      summary: Get an account
      description: Get the details of a specific account.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/account"

  /accounts/{address}/transactions:
    parameters:
      - $ref: "#/components/parameters/address"
    get:
      summary: List account raw transactions
      description: Get a list of all transactions sent by an account.
      parameters:
      - $ref: "#/components/parameters/limit"
      - $ref: "#/components/parameters/offset"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/transaction"
    post:
      summary: Send a raw transaction
      description: Send a transaction from an account. Returns a job.
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/script"
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/job"

  /accounts/{address}/transactions/{transactionId}:
    parameters:
    - $ref: "#/components/parameters/address"
    - $ref: "#/components/parameters/transactionId"
    get:
      summary: Get a raw transaction
      description: Get the details of a raw transaction sent by an account.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/transaction"

  /scripts:
    post:
      summary: Execute a script on chain
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/script"
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                oneOf:
                  -  $ref: "#/components/schemas/cadenceValue"
                  -  $ref: "#/components/schemas/plainValue"
