openapi: 3.0.3
info:
  title: Flow Custodial Wallet API
  version: 0.0.1
servers:
  - url: http://localhost:3000/v1
components:
  schemas:
    account:
      type: object
      properties:
        address:
          type: string
          example: "f8d6e0586b0a20c7"
        createdAt:
          type: string
          example: "2021-04-27T05:49:53.211+00:00"
        updatedAt:
          type: string
          example: "2021-04-27T05:49:53.211+00:00"
    transaction:
      type: object
      properties:
        transactionId:
          type: string
          example: "9613c9689a50a5ed9198dc43839cd90ef39203dfdd7ab54f0fc5ca12f256eef0"
        createdAt:
          type: string
          example: "2021-04-27T05:49:53.211+00:00"
        updatedAt:
          type: string
          example: "2021-04-27T05:49:53.211+00:00"
    job:
      type: object
      properties:
        jobId:
          type: string
          example: "717c25c2-4b54-4588-8f83-72f37ae1a0e8"
        status:
          type: string
          example: "Accepted"
        result:
          type: string
          example: ""
        createdAt:
          type: string
          example: "2021-04-27T05:49:53.211+00:00"
        updatedAt:
          type: string
          example: "2021-04-27T05:49:53.211+00:00"
  parameters:
    address:
      name: address
      in: path
      required: true
      schema:
        type: string
        example: "f8d6e0586b0a20c7"
    jobId:
      name: jobId
      in: path
      required: true
      schema:
        type: string
        example: "717c25c2-4b54-4588-8f83-72f37ae1a0e8"
    tokenName:
      name: tokenName
      in: path
      required: true
      schema:
        type: string
        enum: [FLOW, FUSD]
        example: FLOW
    transactionId:
      name: transactionId
      in: path
      required: true
      schema:
        type: string
        example: "9613c9689a50a5ed9198dc43839cd90ef39203dfdd7ab54f0fc5ca12f256eef0"
paths:
  /jobs:
    get:
      summary: List all jobs
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/job"
  /jobs/{jobId}:
    get:
      summary: Get a job
      parameters:
      - $ref: "#/components/parameters/jobId"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/job"
  /accounts:
    get:
      summary: List all accounts
      description: Get a list of all accounts managed by the wallet service.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/account"
    post:
      summary: Create an account
      description: Create a new account that will be managed by the wallet service. Returns a job.
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/job"
  /accounts/{address}:
    get:
      summary: Get an account
      description: Get the details of a specific account.
      parameters:
      - $ref: "#/components/parameters/address"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/account"
  /accounts/{address}/transactions:
    get:
      summary: List account raw transactions
      description: Get a list of all transactions sent by an account.
      parameters:
      - $ref: "#/components/parameters/address"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/transaction"
    post:
      summary: Send a raw transaction
      description: Send a transaction from an account. Returns a job.
      parameters:
      - $ref: "#/components/parameters/address"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                code:
                  type: string
                arguments:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                      value:
                        type: string
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/job"
  /accounts/{address}/transactions/{transactionId}:
    get:
      summary: Get a raw transaction
      description: Get the details of a raw transaction sent by an account.
      parameters:
      - $ref: "#/components/parameters/address"
      - $ref: "#/components/parameters/transactionId"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/transaction"
